# Generated by Django 4.2.5 on 2023-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='car_id',
            new_name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(db_index=True, max_length=100, verbose_name='customer'),
        ),
    ]
