# Generated by Django 4.2.5 on 2023-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_rename_car_id_serviceorder_car_alter_car_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Completed'), (3, 'Canceled')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(db_index=True, max_length=10, verbose_name='plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, verbose_name='vin'),
        ),
    ]
