# Generated by Django 4.2.5 on 2023-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_serviceorder_status_alter_car_plate_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, unique=True, verbose_name='vin'),
        ),
    ]
