# Generated by Django 4.2.5 on 2023-09-29 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_alter_car_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='partservice',
            name='part_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='part id'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='order id'),
        ),
    ]
