# Generated by Django 4.2.5 on 2023-10-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_partservice_part_id_serviceorder_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partservice',
            options={'ordering': ['-name'], 'verbose_name': 'part service', 'verbose_name_plural': 'part services'},
        ),
    ]
